package com.example.om.domain;

public enum OrderStatus {
    CREATED,
    PENDING_PAYMENT,
    PAYMENT_REJECTED,
    PAYMENT_AUTHORIZED,
    PENDING_INVENTORY,
    INVENTORY_REJECTED,
    INVENTORY_RESERVED,
    PENDING_SHIPPING,
    SHIPMENT_REJECTED,
    COMPLETED,
    COMPENSATING_INVENTORY,
    COMPENSATING_PAYMENT,
    CANCELED
}
