spring.application.name=customer-management-service

# http://localhost:7070/cms/api/v1/swagger-ui/index.html
server.address=localhost
server.port=7070

server.servlet.context-path=/cms
spring.mvc.servlet.path=/api/v1

customerEventsTopic=customer-events

spring.kafka.bootstrap-servers=localhost:9092,localhost:9096,localhost:9097,localhost:9098,localhost:9099
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer