spring.application.name=algotrading-streaming-service

server.address=localhost
server.port=5050

spring.kafka.bootstrap-servers=localhost:9092,localhost:9096,localhost:9097,localhost:9098,localhost:9099
spring.kafka.streams.application-id=algotrading-streaming-service-v1
spring.kafka.streams.state-dir=c:/kafka/kafka-streams-state
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.timestamp.extractor=com.example.algotrading.streaming.stream.TradeTimestampExtractor
spring.kafka.streams.properties.processing.guarantee=at_least_once
spring.kafka.streams.properties.commit.interval.ms=1000
spring.kafka.streams.properties.num.stream.threads=2
spring.kafka.streams.properties.cache.max.bytes.buffering=10485760

trading.analytics.input-topic=trades
trading.analytics.validated-trades-topic=market-analytics.trades.validated
trading.analytics.candle-topic=market-analytics.candles-1m
trading.analytics.vwap-topic=market-analytics.vwap-5m
trading.analytics.alert-topic=market-analytics.alerts
trading.analytics.candle-store-name=ohlcv-1m-store
trading.analytics.vwap-store-name=vwap-5m-store
trading.analytics.candle-window=1m
trading.analytics.vwap-window=5m
trading.analytics.window-grace=10s
trading.analytics.price-range-alert-percentage=0.25

management.endpoints.web.exposure.include=health,info,metrics

spring.threads.virtual.enabled=true

spring.kafka.streams.properties.statestore.cache.max.bytes=10485760
