spring.application.name=customer-service-writemodel
server.port=8101

spring.data.mongodb.uri=${CUSTOMER_WRITE_MONGODB_URI:mongodb://localhost:27017/customer-write-model}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app.kafka.customer-events-topic=${CUSTOMER_EVENTS_TOPIC:crm-es-events}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
