spring.application.name=algotrading-service

server.address=localhost
server.port=4040

resilience4j.retry.instances.kafka.max-attempts=3
resilience4j.retry.instances.kafka.wait-duration=3s
resilience4j.retry.instances.kafka.retry-exceptions=java.lang.Throwable
resilience4j.retry.instances.kafka.enable-exponential-backoff=true
resilience4j.retry.instances.kafka.exponential-backoff-multiplier=2

topicName=trades

spring.kafka.bootstrap-servers=localhost:9092,localhost:9096,localhost:9097,localhost:9098,localhost:9099
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.mongodb.uri=mongodb://localhost:27017/algotrading


spring.threads.virtual.enabled=true